### ISSUE TITLE
Create POST

### ISSUE THREAD

**Issue by Russ716** [NSS-Day-Cohort-58/buttons-server-team-3-1#3]
Users will create an appointment request, which will need to be POSTed to the requests list. 

Define a do_POST(self) to stringify to JSON and create a new request similar to orders in Kneel.

**Comment by Lorin-Jones** [comment]
Add "create_request" function to request_requests.py module

**Comment by Lorin-Jones** [comment]
import create_request function in both views __init__ and request_handler

**Comment by Lorin-Jones** [comment]
Completed
